### PR TITLE
Modernize and require external serializers

### PR DESCRIPTION
**Pull request by TalAmuyal**
asana: https://app.asana.com/0/23095211578528/1203270137996052

### CODE REVIEW

**Review by dorony — APPROVED** [review]

**Comment by mergatron-service** [comment]
Merged Pull Request
- Code reviewed by dorony.
- CI tests passed for commit 2a284ffc3a2e064d4fe5cbb05dfff3f115ef93ee.
- Asana project:
  - Modernize and require external serializers (R&D Board)

**Comment by bennypowers** [comment]
please remove my account from your scripts

I don't need these notifications

I've asked several times already

**Comment by TalAmuyal** [comment]
@bennypowers , 
Sorry, I'll look for it now.

**Comment by mcouthon** [comment]
@bennypowers , could you please share what's the notification you received? We can't find you as configured anywhere in this repo, and we'd like to understand where the notifications are coming from.
Sorry for the inconvenience.

**Pull request merged**
